# Generated by Django 4.0.6 on 2022-08-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='username',
        ),
    ]
